export {default as Home} from './Home/Home'
export {default as EmployeeDetails} from './EmployeeDetails/EmployeeDetails'
export {default as UpdateEmployee} from './UpdateEmployee/UpdateEmployee'
export {default as AddEmployee } from './AddEmployee/AddEmployee'
export {default as AllEmployees } from './AllEmployees/AllEmployees'